### ISSUE TITLE
Merge efforts in one repo

### ISSUE THREAD

**Issue by zenorocha** [Aszarsha/dracula-Xresources#1]
Hello @Aszarsha!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in merging efforts with the existing XResources theme (https://github.com/dracula/xresources). Is there anything you would like to change from that one? Would you be interested in becoming a maintainer on that project?

What do you think?

**Comment by Aszarsha** [comment]
Hello @zenorocha,

As far as I know I already am the maintainer of dracula/xresources, which is an (undirect) fork of this repository. Am I not ? :)

**Comment by zenorocha** [comment]
hahahahah I didn't notice it! Sorry about that.
